### ISSUE TITLE
Intellectual Property, Indigenous Knowledges, and the Rise of Open Data in Australian Environmental Archaeology.

### ISSUE THREAD

**Issue by cemonks** [open-life-science/ols-3#21]
Project Lead: Carly Monks @cemonks

Mentor: Esther Plomp @EstherPlomp

Welcome to OLS-3! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Life Science program :tada:.

***

Week 1 (week starting 8 February 2021): Meet your mentor!
- [x] Create an account on [GitHub](https://github.com)
- [x] Check if you have access to the HackMD notes set up for your meetings with your mentor
- [x] Prepare to meet your mentor(s) by completing a short homework provided in the HackMD notes
- [x] Complete **your own copy** of the [open leadership self-assessment](https://docs.google.com/document/d/1oQgdfj4lPnypAyb9_Ba0Zt7E8J5L6qMvuKwu0wgQsjs/edit?usp=sharing) and share it to your mentor 
  If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (week starting 15 February 2021): Cohort Call (Welcome to Open Life Science!)
- [x] Create an issue on the [OLS-3 GitHub repository](https://github.com/open-life-science/ols-3/issues/new) for your OLS work and share the link to your mentor.
- [x] Draft a brief vision statement using your goals

  [This lesson](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/) from the Open Leadership Training Series (OLTS) might be helpful

- [x] Leave a comment on this issue with your draft vision statement & be ready to share this on the call
- [x] Check the [Syllabus](https://openlifesci.org/ols-3) for notes and connection info for all the cohort calls.

Before Week 3 (week starting 22 February 2021): Meet your mentor!
- [x] Look up two other projects and comment on their issues with feedback on their vision statement
- [x] Complete this [compare and contrast assignment](https://docs.google.com/document/d/1ukvqDRIYfvCapVMdE5hWP-0MkLNJ9T65X43O7F336Ac/edit?usp=sharing) about current and desired community interactions and value exchanges
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://docs.google.com/presentation/d/1MeJo0TyuMg_waLk1J4q9y1aAqKNMuRBlnmxEChSz-cQ/edit?usp=sharing))
- [x] Share a link to your Open Canvas in your GitHub issue
- [x] Start your [Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
- [x] Comment on your issue with your draft Roadmap
- [x] Suggest a cohort name at the bottom of the shared notes and vote on your favorite with a +1

Before Week 4 (week starting 1 March 2021): Cohort Call (Tooling and roadmapping for Open projects)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.

Week 5 and later
- [x] Create a GitHub repository for your project
- [x] Add the link to your repository in your issue
- [x] Use your canvas to [start writing a `README.md` file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project
- [x] Link to your README in a comment on this issue
- [x] Add an [open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) to your repository as a file called `LICENSE.md`
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/) to your repository as a file called `CODE_OF_CONDUCT.md`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Life Science program. Please refer to the [OLS-3 Syllabus](https://openlifesci.org/ols-3) for more detailed weekly notes and assignments past week 4.

**Comment by cemonks** [comment]
**Draft Vision Statement**
_I’m working with Aboriginal communities and archaeologists to develop guidelines for ethical approaches to open data in Australian environmental archaeology so that palaeoenvironmental researchers can openly and fairly share and reuse data to benefit all._

**Comment by cemonks** [comment]
**[Open Canvas Link](https://docs.google.com/presentation/d/185IidMPfEHrrfINsQbnznV5NtACMSNnrs7IBKnlS4ao/edit?usp=sharing)**

**Comment by ejlawrence144** [comment]
This sounds super interesting!

**Comment by AnnaleeSekulic** [comment]
Hey Carly! I really like your angle of work focusing on indigenous knowledge and intellectual property control. I do some work for the society of ethnobiology on decolonization. I would love to connect :)

**Comment by JMMaok** [comment]
> 
> 
> **[Open Canvas Link](https://docs.google.com/presentation/d/185IidMPfEHrrfINsQbnznV5NtACMSNnrs7IBKnlS4ao/edit?usp=sharing)**

Thanks for sharing your open canvas. I think the problem framing worked very well for your project!

**Comment by cemonks** [comment]
> Hey Carly! I really like your angle of work focusing on indigenous knowledge and intellectual property control. I do some work for the society of ethnobiology on decolonization. I would love to connect :)

Hi! That sounds super interesting, would be great to chat more (also your project sounds fascinating!)

**Comment by cemonks** [comment]
## Roadmap
**Project Mission and Summary**
***Intellectual Property, Indigenous Knowledges, and the Rise of Open Data in Australian Environmental Archaeology***

This collaborative project engages Aboriginal communities and archaeologists in the development of guidelines for ethical approaches to open data in Australian environmental archaeology. The goal is to establish a community of practice and clear guidance around collaborative and equitable data sharing and stewardship so that Australian researchers working with palaeoenvironmental data can openly and fairly share and reuse data to benefit all while supporting the rights of Indigenous communities.

### Milestones
**Milestone 1:** Establish a working group of Indigenous and non-Indigenous archaeologists

- [ ] Email 3-4 potential collaborators in AAA and AIAA

- [ ] Collaborators identify and invite 1-2 more potential collaborators to reach preliminary working group of 10-12 people

- [ ] Hold first online meeting to introduce and plan out project


**Milestone 2:** Groundwork for project outputs

- [ ] Review existing guidelines and literature

- [ ] Hold second online meeting to identify key elements: benefits, risks, outputs

- [ ] Draft manuscript on ethical issues and considerations and foreground guidelines

- [ ] Spring 2021: submit manuscript for review

- [ ] December 2021: Present at AAA 2021 Darwin conference


**Milestone 3:** Develop Open Data Guidelines

- [ ] Online workshops/meetings with collaborators to identify important elements for guidelines

- [ ] Develop draft guidelines and resources for implementation

- [ ] Identify key venues for publication of relevant open data (journals and online platforms) and initiate discussions about role of guidelines.

**Comment by WestCorkPalaeo** [comment]
The project vision statement sounds very interesting. The sharing of such information - which deals with sensitive issues - is so crucial, and sorely neglected within the archaeological community generally. What would be the interface to access that you would use?

**Comment by cemonks** [comment]
> The project vision statement sounds very interesting. The sharing of such information - which deals with sensitive issues - is so crucial, and sorely neglected within the archaeological community generally. What would be the interface to access that you would use?

@WestCorkPalaeo do you mean what data sharing platform/repository? I think that would be entirely dependent on the wishes of each particular Indigenous community and is something that needs a lot of further thought!

**Comment by WestCorkPalaeo** [comment]
Thanks Carly - yes, good point, I should have realised that - it will have
to be sensitive to their needs and wishes. But that sort of consultation
will be ideal for building trust and interest I would imagine.

Best regards

*Robin Lewando*
*WestCorkPalaeo,*
*Rearahinagh,*
*Drimoleague,*
*Cork.*

*www.westcorkpalaeo.com <http://www.westcorkpalaeo.com>*

*Mobile: 0830744708*

**Comment by open-phytoliths-admin** [comment]
> **[Open Canvas Link](https://docs.google.com/presentation/d/185IidMPfEHrrfINsQbnznV5NtACMSNnrs7IBKnlS4ao/edit?usp=sharing)**

Hi Carly! Your project sounds very interesting as it will explore the effect of open science practices in archaeological/palaeoecological studies on current indigenous communities. The canvas and roadmap look solid to me. Have you thought about adding a survey to your project to better assess how to improve the interaction between indigenous communities and researchers?

**Comment by cemonks** [comment]
> > **[Open Canvas Link](https://docs.google.com/presentation/d/185IidMPfEHrrfINsQbnznV5NtACMSNnrs7IBKnlS4ao/edit?usp=sharing)**
> 
> Hi Carly! Your project sounds very interesting as it will explore the effect of open science practices in archaeological/palaeoecological studies on current indigenous communities. The canvas and roadmap look solid to me. Have you thought about adding a survey to your project to better assess how to improve the interaction between indigenous communities and researchers?

@open-phytoliths-admin thank you! I hadn't really considered a survey, but I can see that it would potentially be very valuable. However I'm also currently running a survey (and planning a second) in other unassociated projects with similar target populations so I'm hesitant to add another. But that's something that I could easily suggest to collaborators as a potential avenue.

**Comment by cemonks** [comment]
[Project repository](https://github.com/cemonks/Aust-Arch-Ethics-Open-Data)

**Comment by cemonks** [comment]
[Project README](https://github.com/cemonks/Aust-Arch-Ethics-Open-Data/blob/main/README.md)
